### PR TITLE
Make package PSR-4 compatible and package:discover ready

### PR DESCRIPTION
**Pull request by simonschaufi**

### CODE REVIEW

**Comment by simonschaufi** [comment]
Thank you! A new tag would be great ;)

**Comment by thujohn** [comment]
Yes you're right!

I did it ;)

Thank you for your PR.

**Comment by simonschaufi** [comment]
Is the packagist integratrion still working? https://packagist.org/packages/monarobase/country-list I don't see the new tag there.

**Comment by thujohn** [comment]
I just forced the update.

**Comment by simonschaufi** [comment]
> - Updating monarobase/country-list (2.0.0 => 2.1.0): Downloading (100%)

worked! thanx

**Pull request merged**
